import bibtexparser
import os.path

INVIS = "[](@autogenerated - invisible comment)"
with open('all.bib') as bibtex_file:
    bib_database = bibtexparser.load(bibtex_file)

#print(bib_database.entries)


AllRefs = ""
for k in bib_database.entries:
    #print k.keys()
    m = "* "
    if os.path.isfile("ArticlesPDF/"+k["ID"]+".pdf"):
        m += "[x] "
    else:
        m += "[ ] "
    m += "["+k["ID"]+"] __"+k["title"]+"__"
    if "author" in k.keys():
        m += " by "+k["author"]
    #print m.replace("{","").replace("}","")
    if "doi" in k.keys():
        m += ". (_DOI: ["+k["doi"]+"](https://doi.org/"+k["doi"]+")_)."
    AllRefs += m+"\n"

text_file = open("AllRefs.md", "w")
text_file.write(AllRefs.encode('utf8').replace("{","").replace("}","")+"\n"+INVIS)
text_file.close()
